Write-Host "hello world"
Write-Host "hello Daren Alejandro Jofre"
Write-Host "Hello Sebastian"
Write-Host "hello Alexandre"
Write-Host "hello Dylan"
Write-Host "hello Marcos"
Write-Host "hello Andrii"
Write-Host "hello Juanvi"
Write-Host "how are you doing" 
Write-Host "I hope you are doing well"
Write-Host "hola"